### PR TITLE
An Updated Canopy Wind Model based on Massman et al. (2017)

### PR DESCRIPTION
**Pull request by drnimbusrain**
This pull request presents an updated canopy wind profile calculation in the CANACC model, based on a recently improved canopy wind model from Massman et al. (2017). This updated model provides a more physically realistic method for calculating wind speed attenuation for canopies of arbitrary foliage distribution and leaf area. Also, this model overcomes previous shortcomings, in which canopy wind models assume that both the within-canopy wind speed and the canopy structure are uniform with depth (z) throughout the canopy.  The current method in CANACC is based on the empirical formulation of Meyers et al. (1998).

Massman et al. (2017) and Kustas et al. (2018) both show improved agreement with observations using this canopy wind model compared to older methods.  We note that this new model also correctly accounts for a no-slip lower boundary condition (the wind speed at the bottom of the canopy is approximately logarithmic in shape and the wind speed diminishes to zero at the roughness length of the ground surface, i.e., when z < zog), regardless of canopy leaf area density (lad) or canopy structure. We note that currently the CANACC model iterative solution to calculate Tair will need to be updated to account for the no-slip condition, as ubar=0 at z=0 causes NaN values throughout the profile for Tair.

Remaining approximations in the updated model include assuming a constant understory ratio of ground roughness length to canopy height (zog/h) = 0.0025, neglecting both sheltering effects (i.e., reduced foliage drag forces when canopy elements shelter one another; p1=0), and any dependence of the bulk drag coefficient on wind speed (d1=0).  Foliage distribution shape functions are calculated based on associated parameter values set in the canopy data file for known canopy types (e.g., hardwood, pine, corn, rice, etc.).  

In fact, these methods could be further extended to using an equally simple analytical expression for the within-canopy Reynolds stress, i.e., the u*^2(z) profile, which in turn can be used to determine the canopy roughness length and displacement heights.    

Below is a single time step comparison of the current Meyers et al. (1998) and updated Massman et al. (2017) models in CANACC, for the Coweeta Forest site:
 
image

**References:**
Meyers et al. (1998) A multilayer model for inferring dyr deposition using standard meteorological measurements, JGR, 103, D17, 22645-22661.

Massman, W. J.; Forthofer, J. M.; Finney, M. A. 2017. An improved canopy wind model for predicting wind adjustment factors and wildland fire behavior. Canadian Journal of Forest Research. 47: 594-603.

Kustas, W.P., M.C. Anderson, J.G. Alfieri, K. Knipper, A. Torres-Rua, C.K. Parry, H. Nieto, N. Agam, W.A. White, F. Gao, L. McKee, J.H. Prueger, L.E. Hipps, S. Los, M.M. Alsina, L. Sanchez, B. Sams, N. Dokoozlian, M. McKee, S. Jones, Y. Yang, T.G. Wilson, F. Lei, A. McElrone, J.L. Heitman, A.M. Howard, K. Post, F. Melton, and C. Hain, 2018: The Grape Remote Sensing Atmospheric Profile and Evapotranspiration Experiment. Bull. Amer. Meteor. Soc., 99, 1791–1812, https://doi.org/10.1175/BAMS-D-16-0244.1

### CODE REVIEW

**Comment by rdsaylor** [comment]
Patrick, This is a great start to including the Massman wind profile, but I have some concerns about your proposed implementation, as follows:

1. I'd like to see the Massman algorithm added as an option, rather than a replacement for the Meyers algorithm.  Initially, this could be done as I've done the Kv algorithm in ACCESS_FULL/EnvironData.f90.  (I need to do the same thing in CANACC actually.)

2. It's not clear to me how the Massman parameters (e.g., zmaxrho, sigmau, sigma1, fainc, fatot, etc.) interact with the input LAD profile.  Are the Massman parameters calculated from the input LAD profile?  If not, they need to be made consistent somehow.  For the current test case (Coweeta), the LAD profile was actually measured, so whatever the Massman algorithm needs should be consistent with the measured profile. Can you prepare a writeup that describes your implementation so I can understand better how it interacts with a given LAD profile?

3. The u=0 at z=0 is a problem.  There needs to be a minimum wind speed (even at z=0).  Does the Massman algorithm _require_ u=0 or can you set a minimum?  This will need to be fixed before we can move forward with Massman.

**Comment by drnimbusrain** [comment]
Hi Rick,

Thanks for having a look!

Yes, this was only intended as a starting point to test the Massman et al.
wind profile.  In response to your comments:

   1.

   I'd like to see the Massman algorithm added as an option, rather than a
   replacement for the Meyers algorithm. Initially, this could be done as I've
   done the Kv algorithm in ACCESS_FULL/EnvironData.f90. (I need to do the
   same thing in CANACC actually.)

*I agree an option is the right way to go, and we can follow initially what
you suggested with the Kv algorithm in ACCESS. Please let me know, however,
if you or I should head this up, in case you have specific method you would
like to follow closely.   *

   1.

   It's not clear to me how the Massman parameters (e.g., zmaxrho, sigmau,
   sigma1, fainc, fatot, etc.) interact with the input LAD profile. Are the
   Massman parameters calculated from the input LAD profile? If not, they need
   to be made consistent somehow. For the current test case (Coweeta), the LAD
   profile was actually measured, so whatever the Massman algorithm needs
   should be consistent with the measured profile. Can you prepare a writeup
   that describes your implementation so I can understand better how it
   interacts with a given LAD profile?

*In short, the Massman algorithm interacts with the measured the LAD
profile through use of the integrated total LAD (i.e., laitot) in
Initialize.f90.  Specifically, in EnvironData.f90, the laitot is multiplied
by the drag coefficient to get the gamlai variable, i.e, the coefficient of
wind speed attenuation in the canopy.  Then, the gamlai variable is
directly used in the calculation of the hyperbolic cosine term that
dominates near the top of the canopy (i.e., canopytop) and attenuates the
final in-canopy wind speed.  The other terms you note (zmaxrho, sigmau,
sigma1, fainc, fatot) are dependent on the canopy type and its shape
profile.  Thus, there should still be consistency in this application of
Massman algorithm with the measured LAD profile through gamlai.  I can
definitely provide a more thorough writeup on the implementation if we need
more details. *

   1.

   The u=0 at z=0 is a problem. There needs to be a minimum wind speed
   (even at z=0). Does the Massman algorithm *require* u=0 or can you set a
   minimum? This will need to be fixed before we can move forward with Massman.

*In this case, however, the Massman algorithm is based on the physical
principle of the no-slip lower boundary condition.  This seems a sound
theory given that wind speed should be logarithmic in the bottom of the
canopy, and wind speed diminishes to exactly zero at the roughness length
of the ground surface.  Thus it physically requires ubar=0 at z=0.  I have
tested this by making it go to a minimum value above zero at z = 0, but it
leads to erroneous values in the Massman algorithm.  The no-slip boundary
is a principle of fluid dynamics, such that the no-slip condition for
viscous fluids assumes that at a solid boundary, the fluid will have zero
velocity.  Basically, the molecules in the fluid flow should crash into the
lower boundary and the flow should stop at z=0.   I think the no-slip
condition is applied across other CFD and atmospheric grid models.*

Please let me know what you think.

Thank you,

Patrick

**Comment by rdsaylor** [comment]
Patrick,

- Go ahead and give it a shot in making the Massman algorithm as an option in CANACC.  You can just do it internally first with a hard-coded selection variable.  Ultimately, it would be an option set in the simulation control file (i.e., in accessCTRL.dat).

- I _would_ like to see a writeup of the algorithm as you've implemented it.  I've read through the Massman paper once but I need to look at it closer to really understand it.

- The no-slip condition is fine for calculating the wind speed profile if that's what it depends on.  We can't actually use a u=0 value however in the model.  We'll need to come up with a reasonable way to set some non-zero value at the surface for subsequent calculations that need u (i.e., let the Massman algorithm do its thing and produce the u=0 and z=0, but then substitute some derived value for use by other calculations that depend on u(z=0)).  A simple possibility would be to set u(0) = 0.5*u(1), but I'm sure you can come up with something better.

Thanks again for working on this.

**Comment by drnimbusrain** [comment]
Thank you Rick for the reply.

I will work on those three items, and do another pull request when
completed (with formal CANACC implementation writeup).

For number 3, I guess I still have questions as to why the real fluid
condition of u=0 at z = 0 (no-slip) can't be used in the model, but I will
try a simple fix to make u(0) > zero outside of the Massman wind speed
algorithm call so it doesn't break the other parts of CANACC code.  We can
discuss this some other time.

I find this and your ACCESS code very interesting.  I am currently trying
to include some aspects of it into our upcoming FV3-Chem proposal.

Thanks again for collaborating,

Patrick

**Comment by drnimbusrain** [comment]
Hi Rick,

Hope all is well, and based on what we discussed I have pushed the updated
Massman wind model to your CANACC development branch.

I will send you a draft soon of a formal write up for the Massman
implementation in CANACC.

I hope you are weathering the shutdown as best as possible, and hope to be
back at work soon!

Thank you,

Patrick

**Comment by drnimbusrain** [comment]
Hi Rick,

Attached is a first draft of the Massman canopy wind model formal write-up
for the CANACC implementation.  If you have time to review and provide any
edits, comments or suggestions, I highly appreciate it.

Thank you,

Patrick

**Pull request closed without merging**
